title: Zhidi Zhang
description: A resilient soul who rose from the ashes, harnessing strength and determination to rewrite their own destiny.
theme: jekyll-theme-cayman
# theme: jekyll-theme-dinky
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
#   - jekyll-remote-theme

# add this line to the plugins list if you already have one
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
