title: Zhidi Zhang # your name (or website title) here
logo: "/images/cat_logo.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description: My name is Shizuka.
  <br><br>
  Second description 
  <br><br>
  <a href="www.linkedin.com/in/zhidi-zhang">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://github.com/DidiQut">View My Github Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
